rules:
  empty-line-between-blocks: 0
  force-element-nesting: 0
  no-duplicate-properties: 0
  no-vendor-prefixes: 0
  no-color-literals: 0
  one-declaration-per-line: 0
  property-sort-order: 0
  force-pseudo-nesting: 0
  quotes:
    - 1
    -
      style:
        - double
  nesting-depth:
    - 1
    -
      max-depth:
        - 4
